{{ config(
  post_hook = "alter table {{ this }} add row access policy PRODUCTION_DB.POLICIES.EMPLOYEES_POLICY on (TEAM);
                GRANT USAGE ON DATABASE PRODUCTION_DB TO ROLE TEAM_MANAGER_1;
                GRANT USAGE ON WAREHOUSE TEAM_MANAGER_WH TO ROLE TEAM_MANAGER_1;
                GRANT USAGE ON SCHEMA PRODUCTION_DB.FINAL TO ROLE TEAM_MANAGER_1;
                GRANT SELECT ON TABLE PRODUCTION_DB.FINAL.EMPLOYEES TO ROLE TEAM_MANAGER_1;
                GRANT USAGE ON DATABASE PRODUCTION_DB TO ROLE TEAM_MANAGER_2;
                GRANT USAGE ON WAREHOUSE TEAM_MANAGER_WH TO ROLE TEAM_MANAGER_2;
                GRANT USAGE ON SCHEMA PRODUCTION_DB.FINAL TO ROLE TEAM_MANAGER_2;
                GRANT SELECT ON TABLE PRODUCTION_DB.FINAL.EMPLOYEES TO ROLE TEAM_MANAGER_2;
                GRANT USAGE ON DATABASE PRODUCTION_DB TO ROLE ANALYST_ROLE;
                GRANT USAGE ON WAREHOUSE ANALYST_WH TO ROLE ANALYST_ROLE;
                GRANT USAGE ON SCHEMA FINAL TO ROLE ANALYST_ROLE;
                GRANT USAGE ON SCHEMA FINAL_CUSTOMER_SCHEMA TO ROLE ANALYST_ROLE;
                GRANT SELECT ON ALL TABLES IN SCHEMA FINAL TO ROLE ANALYST_ROLE;
                GRANT SELECT ON ALL TABLES IN SCHEMA FINAL_CUSTOMER_SCHEMA TO ROLE ANALYST_ROLE;
                REVOKE SELECT ON TABLE PRODUCTION_DB.FINAL.MANAGER_TABLE FROM ROLE ANALYST_ROLE;"
) }}

SELECT EMPLOYEE_ID
        , TO_DATE(DATE_1, 'DD-MM-YYYY')                     AS START_DATE
        , TO_DATE(DATE_2, 'DD-MM-YYYY')                      AS END_DATE
        , TEAM
FROM {{ source('public', 'employees') }}